.\" Manpage for passgen.
.\" Contact cristi@tiurbe.ro to correct errors or typos.
.TH man 7 "16 July 2015" "1.0" "passgen man page"
.SH NAME
passgen \- generate random passwords
.SH SYNOPSIS
passgen [options]
.SH DESCRIPTION
passgen is a tool for generating random passwords.
.SH OPTIONS
.TP
.B \-\^l " len"
Specify the length of the generated passwords
.B \-l
.TP
.B \-\^c " count"
Specify how many random passwords you want to be generated
.B \-c
.TP
.B \-\^a
Passwords will contain only small letters
.B \-a
.TP
.B \-\^A
Passwords will contain both small and capital letters
.B \-A
.TP
.B \-\^n
Passwords will contain small letters, capital letters and numbers
.B 
.TP
.B \-\^s
Passwords will contain small letters, capital letters, numbers and symbols
.B \-s

.SH SEE ALSO
passgen.sh(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Cristi Tiurbe (cristi@tiurbe.ro)
